server:
  port: 8080

spring:
  application:
    name: task-manager

  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: postgres
    password: Blaze2326@
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ThisIsAMassiveSecretKeyForTaskFlowApplicationThatIsBase64Safe123
  expiration-ms: 86400000
